<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de_DE">
<context>
    <name>QtDataSync::DatabaseWatcher</name>
    <message>
        <location filename="../datasync/databasewatcher.cpp" line="+475"/>
        <source>Failed to get last synced time for table %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+292"/>
        <source>Failed to modify local data %1!</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+3"/>
        <source>Corrupted metadata table for %1 - try to re-synchronize it!</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Corrupted synchronization system table%1. Try to re-synchronize all tables!</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+4"/>
        <source> (Accessing for %1)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+2"/>
        <source>An SQL error occured, unable to synchronize data! Try restarting the engine or re-synchronize all tables.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtDataSync::Engine</name>
    <message>
        <location filename="../datasync/engine.cpp" line="+94"/>
        <source>Cannot resync database while already synchronizing</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cannot resync table while already synchronizing</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+382"/>
        <source>Failed to delete user from authentication server</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtDataSync::FirebaseAuthenticator</name>
    <message>
        <location filename="../datasync/authenticator.cpp" line="+166"/>
        <source>Failed renew firebase connection! Please try to sign in again.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtDataSync::OAuthAuthenticator</name>
    <message>
        <location line="+87"/>
        <source>Sign-In aborted!</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Another account with the same credentials already exists! You have to log in with that account instead or link the two accounts!</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Google Authentication was not accepted by firebase</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Failed to sign in with Google-Account!</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtDataSync::RemoteConnector</name>
    <message>
        <location filename="../datasync/remoteconnector.cpp" line="+171"/>
        <source>Failed to remove table from server</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Failed to delete user from server</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+79"/>
        <source>Live-synchronization connection broken, trying to reconnect…</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Failed to upload data</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+72"/>
        <source>Live-synchronization was stopped by the remote server</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+3"/>
        <source>Live-synchronization expired, reconnecting…</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="-260"/>
        <source>Failed to verify data version before uploading</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="-77"/>
        <location line="+23"/>
        <location line="+32"/>
        <location line="+30"/>
        <location line="+19"/>
        <location line="+138"/>
        <source>User is not logged in yet</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="-195"/>
        <source>Failed to download latests changed data</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+153"/>
        <source>Live-synchronization disabled because of network error!</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
